import type { Metadata } from "next";
import localFont from "next/font/local";
import { GeistSans } from "geist/font/sans";

import "./globals.css";

import Script from "next/script";
import { metadataConfig } from "@/config/metadata";

import { cn } from "@/lib/utils";

const cal_sans = localFont({
  src: "../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: `%s | ${metadataConfig.title}`,
    default: metadataConfig.title, // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={`${GeistSans.variable} ${cal_sans.variable}`}
    >
      {/*    <Script id="theme-switcher" strategy="beforeInteractive">*/}
      {/*      {`if (localStorage.getItem('theme') === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {*/}
      {/*  document.documentElement.classList.add('dark')*/}
      {/*} else {*/}
      {/*  document.documentElement.classList.remove('dark')*/}
      {/*}`}*/}
      {/*    </Script>*/}
      <body className={cn("min-h-screen antialiased")}>{children}</body>
    </html>
  );
}
